// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mochi-yu/websocket-practice/ent/message"
	"github.com/mochi-yu/websocket-practice/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[0].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescAuthorName is the schema descriptor for author_name field.
	messageDescAuthorName := messageFields[1].Descriptor()
	// message.AuthorNameValidator is a validator for the "author_name" field. It is called by the builders before save.
	message.AuthorNameValidator = messageDescAuthorName.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[2].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
}
